# 1. Block này tự động chuyển hướng HTTP sang HTTPS cho CẢ 2 DOMAIN
server {
    listen 80;
    server_name shoeshopecommerce.dpdns.org api.shoeshopecommerce.dpdns.org;
    return 301 https://$host$request_uri;
}

# 2. Block HTTPS cho FRONTEND (Giao diện React/Vite)
server {
    listen 443 ssl;
    server_name shoeshopecommerce.dpdns.org;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}

# 3. Block HTTPS cho BACKEND API (Chuyển tiếp đến Spring Boot)
server {
    listen 443 ssl;
    server_name api.shoeshopecommerce.dpdns.org;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    location / {
        proxy_pass http://localhost:8080; # Trỏ về Spring Boot
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}