apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  labels: {{ include "frontend-chart.selectorLabels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "frontend-chart.selectorLabels" . | nindent 6 }}
  template: 
    metadata:
      labels: {{ include "frontend-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }} 
        ports:
          containerPort: {{ .Values.service.port }}
          name: {{ .Values.service.name  }}

        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf

      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "frontend-chart.fullname" . }}-configmap


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
